# Generated by Django 4.2.5 on 2023-09-11 01:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vi_api', '0002_userdata_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
